### ISSUE TITLE
Wie mache ich einen Toast Hawaii?

### ISSUE THREAD

**Issue by willAiii** [RocketRene/LemonAiders#1]
Schmeckt lecker, habe aber keinen Plan.

**Comment by RocketRene** [comment]
Bin dran

**Comment by willAiii** [comment]
Der Hunger wird nicht weniger

**Comment by RocketRene** [comment]
[toast hawai Production Build Skript ](https://www.brigitte.de/rezepte/toast-hawaii-10542246.html)
